include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    unnecessary_await_in_return: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    require_trailing_commas: true